import type { Metadata } from "next";
import "./globals.css";

import { TRPCReactProvider } from "@/src/trpc/client";
import { Toaster } from "@/src/components/ui/sonner";

import localFont from "next/font/local";

const dana = localFont({
  src: "../../../public/font/DanaVF.woff2",
  variable: "--font-dana",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa" className={dana.variable}>
      <body className={`${dana.className} text-right`}>
        <TRPCReactProvider>
          {children}
          <Toaster />
          </TRPCReactProvider>
      </body>
    </html>
  );
}
