/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    'shipping-settings': ShippingSetting;
    orders: Order;
    reviews: Review;
    'contact-messages': ContactMessage;
    'blog-posts': BlogPost;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      subcategories: 'categories';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'shipping-settings': ShippingSettingsSelect<false> | ShippingSettingsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  roles?: ('super-admin' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  color?: string | null;
  order?: number | null;
  parent?: (string | null) | Category;
  subcategories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  category: string | Category;
  subcategory?: (string | null) | Category;
  price: number;
  discountPrice?: number | null;
  /**
   * میتوانید درصد را manually وارد کنید
   */
  discountPercent?: number | null;
  images?:
    | {
        image?: (string | null) | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * برای هر ترکیب رنگ و سایز، یک ردیف اضافه کنید
   */
  inventory?:
    | {
        colorName: string;
        /**
         * اختیاری - برای نمایش در سایت
         */
        colorHex?: string | null;
        size: string;
        stock: number;
        /**
         * کد محصول برای این ترکیب خاص
         */
        sku?: string | null;
        id?: string | null;
      }[]
    | null;
  sku: string;
  refundPolicy?: ('30-day' | '14-day' | '7-day' | '3-day' | '1-day' | 'no-refunds') | null;
  featured?: boolean | null;
  /**
   * تعداد کل فروش این محصول
   */
  salesCount?: number | null;
  /**
   * مجموع موجودی همه رنگ‌ها و سایزها
   */
  totalStock?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-settings".
 */
export interface ShippingSetting {
  id: string;
  name: string;
  enabled?: boolean | null;
  baseCost: number;
  freeThreshold: number;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber: string;
  status: 'pending' | 'paid' | 'processing' | 'ready_to_ship' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  customer: {
    user?: (string | null) | User;
    fullName: string;
    phone: string;
    email?: string | null;
    address: string;
    city: string;
    postalCode: string;
    notes?: string | null;
  };
  items: {
    product: string | Product;
    productName: string;
    variant?: {
      colorName?: string | null;
      size?: string | null;
      sku?: string | null;
    };
    quantity: number;
    unitPrice: number;
    totalPrice: number;
    id?: string | null;
  }[];
  pricing: {
    subtotal: number;
    /**
     * هزینه ارسال از CMS دریافت می‌شود
     */
    shippingCost: number;
    discount?: number | null;
    /**
     * محاسبه خودکار: (جمع محصولات + هزینه ارسال) - تخفیف
     */
    total: number;
  };
  shipping?: {
    method?: string | null;
    trackingNumber?: string | null;
    estimatedDelivery?: string | null;
  };
  payment: {
    method: 'zarinpal' | 'bank' | 'cod';
    /**
     * شناسه تراکنش دریافتی از زرین‌پال
     */
    transactionId?: string | null;
    /**
     * کد مرجع پرداخت برای پیگیری
     */
    refId?: string | null;
    paymentDate?: string | null;
    paymentStatus?: ('pending' | 'success' | 'failed' | 'cancelled' | 'refunded') | null;
  };
  metadata?: {
    ip?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  title: string;
  توضیحات: string;
  امتیاز: number;
  محصول: string | Product;
  کاربر: string | User;
  status: 'pending' | 'published' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  phone: string;
  subject: 'product-support' | 'order-question' | 'collaboration' | 'feedback' | 'other';
  message: string;
  status?: ('new' | 'read' | 'replied' | 'archived') | null;
  read?: boolean | null;
  productId?: (string | null) | Product;
  adminNotes?: string | null;
  repliedAt?: string | null;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  contentBlocks?:
    | {
        type?: ('text' | 'image' | 'video' | 'gallery' | 'quote' | 'heading') | null;
        title?: string | null;
        headingLevel?: ('h2' | 'h3' | 'h4') | null;
        textContent?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (string | null) | Media;
        gallery?:
          | {
              image?: (string | null) | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        videoUrl?: string | null;
        quote?: string | null;
        quoteAuthor?: string | null;
        alignment?: ('left' | 'center' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  featuredImage: string | Media;
  tags?: ('seasonal-trends' | 'styling' | 'clothing-care' | 'discounts' | 'news')[] | null;
  readingTime?: number | null;
  status?: ('draft' | 'pending' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  views?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'shipping-settings';
        value: string | ShippingSetting;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: string | ContactMessage;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  order?: T;
  parent?: T;
  subcategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  category?: T;
  subcategory?: T;
  price?: T;
  discountPrice?: T;
  discountPercent?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  inventory?:
    | T
    | {
        colorName?: T;
        colorHex?: T;
        size?: T;
        stock?: T;
        sku?: T;
        id?: T;
      };
  sku?: T;
  refundPolicy?: T;
  featured?: T;
  salesCount?: T;
  totalStock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-settings_select".
 */
export interface ShippingSettingsSelect<T extends boolean = true> {
  name?: T;
  enabled?: T;
  baseCost?: T;
  freeThreshold?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  customer?:
    | T
    | {
        user?: T;
        fullName?: T;
        phone?: T;
        email?: T;
        address?: T;
        city?: T;
        postalCode?: T;
        notes?: T;
      };
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        variant?:
          | T
          | {
              colorName?: T;
              size?: T;
              sku?: T;
            };
        quantity?: T;
        unitPrice?: T;
        totalPrice?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        subtotal?: T;
        shippingCost?: T;
        discount?: T;
        total?: T;
      };
  shipping?:
    | T
    | {
        method?: T;
        trackingNumber?: T;
        estimatedDelivery?: T;
      };
  payment?:
    | T
    | {
        method?: T;
        transactionId?: T;
        refId?: T;
        paymentDate?: T;
        paymentStatus?: T;
      };
  metadata?:
    | T
    | {
        ip?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  title?: T;
  توضیحات?: T;
  امتیاز?: T;
  محصول?: T;
  کاربر?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  read?: T;
  productId?: T;
  adminNotes?: T;
  repliedAt?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  contentBlocks?:
    | T
    | {
        type?: T;
        title?: T;
        headingLevel?: T;
        textContent?: T;
        image?: T;
        gallery?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        videoUrl?: T;
        quote?: T;
        quoteAuthor?: T;
        alignment?: T;
        id?: T;
      };
  featuredImage?: T;
  tags?: T;
  readingTime?: T;
  status?: T;
  publishedAt?: T;
  views?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}